### ISSUE TITLE
Update to elm 0.18

### ISSUE THREAD

**Issue by A5308Y** [NoRedInk/elm-rails#13]
Hi there,

I'd love to upgrade my rails-elm project to elm 0.18. Do you have a timeline for upgrading elm-rails to 0.18?

Thanks!

**Comment by eeue56** [comment]
I'll try and do it today

**Comment by A5308Y** [comment]
Wow! I didn't expect something that quick. Today would be amazing!

**Comment by A5308Y** [comment]
Hi there,

Do you have an estimate on when the upgrade can be done? I could try to help, but I'd have to learn all about the http package and the native part. I'm unsure if I would be useful here. Especially when someone's already on it.

**Comment by eeue56** [comment]
Hey there - sorry for the slowness here. I took a look into it last week and it's gonna be a bit more complicated to upgrade than previous expected because of the changes to the way Http works. But, nonetheless I hope to upgrade it today/tomorrow. It's the last package left for us to upgrade but unforunately I had higher prioritises last week

**Comment by A5308Y** [comment]
Sounds good! Thanks for letting me know!

**Comment by A5308Y** [comment]
Hi there!

Any news on how the upgrade is going?

**Comment by eeue56** [comment]
merged here: https://github.com/NoRedInk/elm-rails/pull/14 

and published as 5.0.0!

**Comment by A5308Y** [comment]
Ah perfect! Thanks! I'll try it out right away.

**Comment by A5308Y** [comment]
I see a debugger! Thanks for your work!
